spring:
  application:
    name: eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true

---

spring:
  profiles: eureka-1
server:
  port: 8761eureka:
  instance:
    hostname: eureka-1
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka/}
  
---

spring:
  profiles: eureka-2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  
  